# Generated by Django 5.0.4 on 2024-04-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="picture",
            name="name",
            field=models.TextField(
                default="SomePicture", verbose_name="Name of the picture"
            ),
            preserve_default=False,
        ),
    ]
