# Generated by Django 4.2.11 on 2024-05-02 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_picture_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2024, 5, 2, 15, 21, 36, 560781, tzinfo=datetime.timezone.utc), verbose_name='Date the picture was added'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picture',
            name='description',
            field=models.TextField(null=True, verbose_name='Description of the picture'),
        ),
        migrations.AddField(
            model_name='picture',
            name='tags',
            field=models.TextField(default='', verbose_name='String of space-separated tags related to the picture'),
        ),
    ]
